source s_ise_udp { udp(ip(0.0.0.0) port(5514)); };
# source s_ise_tcp { tcp(ip(0.0.0.0) port(5514)); };
destination d_ise { file("/var/log/ise/${HOST}/${HOST}.log" create-dirs(yes) perm(0644) owner("splunk") group("splunk") dir_perm(0755)); };

# Parsers
block parser cisco-ise-parser() {
    channel { 
        parser {
            csv-parser(columns('1','2','3','MSG') flags(greedy));
            grouping-by(
                        scope("host")
                        key("$1")
                        sort-key('$3')
                        trigger("$(context-length)" eq "$2")
                        timeout(30)
                        aggregate(
                            inherit-mode(last-message)
                            #value("MESSAGE", '$(if "$(context-length) eq $2"  truncated)')
                            value("MESSAGE", "$(if ('$(context-length)' eq '$(+ $2 1)') 
                                                        '$1 1 0 $(implode \" \" $(list-slice :-1 $(context-values $MSG)))'
                                                        '$1 1 0 SYSLOG TRUNCATED $(list-slice :-1 $(context-values $3-$MSG))')")
                            tags(".cise.joined_message"))
            );
        };
        filter { tags(".cise.joined_message"); };
    };
};
log { source(s_ise_udp); parser {cisco-ise-parser()}; destination(d_ise); };
# log { source(s_ise_tcp); parser {cisco-ise-parser()}; destination(d_ise); };